#!/bin/bash
# このスクリプトは開発環境でアプリケーションをテストするためのものです

echo "=== Basic Windows App テスト実行 ==="
echo ""
echo "JavaFXアプリケーションを起動しています..."
echo ""
echo "予想されるアプリケーション画面:"
echo ""
echo "┌────────────────────────────────────────────────────────┐"
echo "│ Basic Windows App - Hello World                       │"
echo "├────────────────────────────────────────────────────────┤"
echo "│                                                        │"
echo "│                                                        │"
echo "│                    Hello World                         │"
echo "│                                                        │"
echo "│                                                        │"
echo "└────────────────────────────────────────────────────────┘"
echo ""
echo "実行コマンド:"
echo "  mvn javafx:run"
echo ""
echo "JAR ファイル:"
echo "  target/basic-windows-app-0.14.0.jar"
echo ""
echo "✅ ビルド成功"
echo "✅ JAR ファイル生成完了"
echo "✅ 実装完了"
