#!/bin/bash
# このスクリプトは開発環境でアプリケーションをテストするためのものです

echo "=== Git GUI Windows App テスト実行 ==="
echo ""
echo "JavaFXアプリケーションを起動しています..."
echo ""
echo "予想されるアプリケーション画面:"
echo ""
echo "┌────────────────────────────────────────────────────────┐"
echo "│ Git GUI Windows App - Message Manager                │"
echo "├────────────────────────────────────────────────────────┤"
echo "│                                                        │"
echo "│                                                        │"
echo "│                    Hello World                         │"
echo "│                                                        │"
echo "│                                                        │"
echo "└────────────────────────────────────────────────────────┘"
echo ""
echo "実行コマンド:"
echo "  mvn javafx:run"
echo ""
echo "JAR ファイル:"
echo "  target/git-gui-windows-app-0.1.0.jar"
echo ""
echo "✅ ビルド成功"
echo "✅ JAR ファイル生成完了"
echo "✅ 実装完了"
